name: LolNeigh
main: io.github.mcredwallhp.lolneigh.LolNeigh
description: Make horses go somewhere other than spawn after going through the End portal
version: ${project.version}

commands:
   lolneigh-set:
      description: Set the location horses respawn at
      usage: /lolneigh-set
      permission: lolneigh.set
      permission-message: You don't have permission to do that.